### ISSUE TITLE
plots of ss data for rrul_be_nflows not working

### ISSUE THREAD

**Issue by peteheist** [tohojo/flent#105]
I should have posted this here instead of on the make-wifi-fast mailing list. :)

I’ve been making use of the —socket-stats / tcp_* plots. They're very useful! However, the plots don't seem to work for rrul_be_nflows tests (in this case I was trying to make an svg and there were 64 upload stream and 64 download streams):

+ flent -i *.flent.gz -p tcp_rtt -o tcp_rtt.svg
Started Flent 1.0.1-git-87a8f96 using Python 2.7.12.
Initialised matplotlib v1.5.1 on numpy v1.11.0.
Traceback (most recent call last):
 File "/usr/local/bin/flent", line 9, in <module>
   load_entry_point('flent===1.0.1-git-87a8f96', 'console_scripts', 'flent')()
 File "/usr/local/lib/python2.7/dist-packages/flent-1.0.1_git_87a8f96-py2.7.egg/flent/__init__.py", line 56, in run_flent
   b.run()
 File "/usr/local/lib/python2.7/dist-packages/flent-1.0.1_git_87a8f96-py2.7.egg/flent/batch.py", line 559, in run
   return self.load_input(self.settings)
 File "/usr/local/lib/python2.7/dist-packages/flent-1.0.1_git_87a8f96-py2.7.egg/flent/batch.py", line 540, in load_input
   formatter.format(results)
 File "/usr/local/lib/python2.7/dist-packages/flent-1.0.1_git_87a8f96-py2.7.egg/flent/formatters.py", line 388, in format
   self.plotter.save(results)
 File "/usr/local/lib/python2.7/dist-packages/flent-1.0.1_git_87a8f96-py2.7.egg/flent/plotters.py", line 654, in save
   save_args = self.build_tight_layout(artists)
 File "/usr/local/lib/python2.7/dist-packages/flent-1.0.1_git_87a8f96-py2.7.egg/flent/plotters.py", line 791, in build_tight_layout
   self.figure.tight_layout(pad=0.5, rect=rect)
 File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1756, in tight_layout
   self.subplots_adjust(**kwargs)
 File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1612, in subplots_adjust
   self.subplotpars.update(*args, **kwargs)
 File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 230, in update
   raise ValueError('bottom cannot be >= top')
ValueError: bottom cannot be >= top

**Comment by dtaht** [comment]
Toke is on a (very big) boat near the arctic circle and won't be back for a bit.

I'm loving this new facility too...

**Comment by peteheist** [comment]
Toke, in case there's time in the Arctic, please fix climate change as well. :)

**Comment by tohojo** [comment]
Pete Heist <notifications@github.com> writes:

> Toke, in case there's time in the Arctic, please fix climate change as
> well. :)

Gave it my best shot, but not sure it'll be enough... ;)

Will get around to looking at your bug report once I'm through my
backlog of email.

-Toke

**Comment by peteheist** [comment]
Thanks, works great. :)
