### ISSUE TITLE
flent-gui crashes while running test

### ISSUE THREAD

**Issue by huaracheguarache** [tohojo/flent#261]
I tried to run a rrul_be test with flent-gui, but I got the following crash:

```
[michael@localhost ~]$ flent --gui
Starting Flent 2.0.1 using Python 3.10.2.
Initialised matplotlib v3.5.1 on numpy v1.21.5.
QSocketNotifier: Can only be used with threads started with QThread
GUI loaded. Using Qt through pyqt5 v5.15.2.
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Starting rrul_be test. Expected run time: 310 seconds.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flent/gui.py", line 1034, in update_progress
    self.progressBar.setValue(100 * elapsed / self.total_time)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flent/gui.py", line 1034, in update_progress
    self.progressBar.setValue(100 * elapsed / self.total_time)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
Aborted (core dumped)
[michael@localhost ~]$ Traceback (most recent call last):
  File "/usr/lib64/python3.10/multiprocessing/queues.py", line 251, in _feed
    send_bytes(obj)
  File "/usr/lib64/python3.10/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib64/python3.10/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/usr/lib64/python3.10/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
```

**Comment by huaracheguarache** [comment]
Ok, now it works. Thanks! =)
