### ISSUE TITLE
Blank window on start (Flent 2.1.1, macOS)

### ISSUE THREAD

**Issue by richb-hanover** [tohojo/flent#293]
I installed `flent` using pip on my macOS 12.7.2 machine. Running `flent-gui` from the command line was surprising:

- The `flent` window opened and displays "GUI Loaded using ..." briefly in the bar at the bottom left of the window.
- That legend disappeared.
- Nothing else happened... I wondered if there was some weird Qt/Python/system problem.
- Eventually, I farbled around in the menus and found **Run new test Cmd-R** which worked as expected.

My request: If no other action is specified, perhaps the **Run new test** could occur by default. Many thanks.

**Comment by richb-hanover** [comment]
Looks good. 

<img width="904" alt="image" src="https://github.com/tohojo/flent/assets/1094930/320b2b7b-ce0a-4b2b-bdaf-887bc36feb9c">

Since we're talking about defaults, could the "Run new test" suggest RRUL by default? It's highly likely that this what newcomers want, and experienced users can choose their favorite. Thanks.

------------
BTW: I saw this output when running Cubic Reno (which I selected by mistake...) It displayed error messages in the GUI, and the log file showed:

```
√ flent % /Users/richb/.pyenv/versions/3.7.4/bin/flent-gui
Starting Flent 2.1.1+git.1f6452a5 using Python 3.7.4.
Initialised matplotlib v3.1.1 on numpy v1.21.6.
qt.qpa.fonts: Populating font family aliases took 711 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.
GUI loaded. Using Qt through pyqt5 v5.15.11.
Starting cubic_reno test. Expected run time: 70 seconds.
WARNING: Program exited non-zero.
Runner class: NetperfDemoRunner
Command: /usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x0,0x0 -H 192.168.253.129 -p 12865 -t TCP_MAERTS -l 60 -F /dev/urandom -f m   --    -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K reno
Return code: 255
Stdout: establish control: are you sure there is a netserver listening on 192.168.253.129 at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to 192.168.253.129 port 12865 address family AF_INET

Stderr: 1705515396.162844: PID 76864 sleeping for 5 seconds
1705515401.164265: PID 76864 running execvpe(/usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x0,0x0 -H 192.168.253.129 -p 12865 -t TCP_MAERTS -l 60 -F /dev/urandom -f m -- -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K reno)

WARNING: Program exited non-zero.
Runner class: NetperfDemoRunner
Command: /usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x20,0x20 -H 192.168.253.129 -p 12865 -t TCP_STREAM -l 60 -F /dev/urandom -f m   --    -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K cubic
Return code: 255
Stdout: establish control: are you sure there is a netserver listening on 192.168.253.129 at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to 192.168.253.129 port 12865 address family AF_INET

Stderr: 1705515396.152639: PID 76861 sleeping for 5 seconds
1705515401.153617: PID 76861 running execvpe(/usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x20,0x20 -H 192.168.253.129 -p 12865 -t TCP_STREAM -l 60 -F /dev/urandom -f m -- -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K cubic)

WARNING: Program exited non-zero.
Runner class: NetperfDemoRunner
Command: /usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x20,0x20 -H 192.168.253.129 -p 12865 -t TCP_STREAM -l 60 -F /dev/urandom -f m   --    -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K reno
Return code: 255
Stdout: establish control: are you sure there is a netserver listening on 192.168.253.129 at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to 192.168.253.129 port 12865 address family AF_INET

Stderr: 1705515396.156497: PID 76862 sleeping for 5 seconds
1705515401.157939: PID 76862 running execvpe(/usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x20,0x20 -H 192.168.253.129 -p 12865 -t TCP_STREAM -l 60 -F /dev/urandom -f m -- -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K reno)

WARNING: Program exited non-zero.
Runner class: NetperfDemoRunner
Command: /usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x0,0x0 -H 192.168.253.129 -p 12865 -t TCP_MAERTS -l 60 -F /dev/urandom -f m   --    -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K cubic
Return code: 255
Stdout: establish control: are you sure there is a netserver listening on 192.168.253.129 at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to 192.168.253.129 port 12865 address family AF_INET

Stderr: 1705515396.1614442: PID 76863 sleeping for 5 seconds
1705515401.162272: PID 76863 running execvpe(/usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x0,0x0 -H 192.168.253.129 -p 12865 -t TCP_MAERTS -l 60 -F /dev/urandom -f m -- -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K cubic)

WARNING: Program exited non-zero.
Runner class: NetperfDemoRunner
Command: /usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x20,0x20 -H 192.168.253.129 -p 12865 -t TCP_MAERTS -l 60 -F /dev/urandom -f m   --    -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K cubic
Return code: 255
Stdout: establish control: are you sure there is a netserver listening on 192.168.253.129 at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to 192.168.253.129 port 12865 address family AF_INET

Stderr: 1705515396.167041: PID 76865 sleeping for 5 seconds
1705515401.1678998: PID 76865 running execvpe(/usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x20,0x20 -H 192.168.253.129 -p 12865 -t TCP_MAERTS -l 60 -F /dev/urandom -f m -- -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K cubic)

WARNING: Program exited non-zero.
Runner class: NetperfDemoRunner
Command: /usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x0,0x0 -H 192.168.253.129 -p 12865 -t TCP_STREAM -l 60 -F /dev/urandom -f m   --    -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K reno
Return code: 255
Stdout: establish control: are you sure there is a netserver listening on 192.168.253.129 at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to 192.168.253.129 port 12865 address family AF_INET

Stderr: 1705515396.149002: PID 76860 sleeping for 5 seconds
1705515401.1507819: PID 76860 running execvpe(/usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x0,0x0 -H 192.168.253.129 -p 12865 -t TCP_STREAM -l 60 -F /dev/urandom -f m -- -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K reno)

WARNING: Program exited non-zero.
Runner class: NetperfDemoRunner
Command: /usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x0,0x0 -H 192.168.253.129 -p 12865 -t TCP_STREAM -l 60 -F /dev/urandom -f m   --    -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K cubic
Return code: 255
Stdout: establish control: are you sure there is a netserver listening on 192.168.253.129 at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to 192.168.253.129 port 12865 address family AF_INET

Stderr: 1705515396.146147: PID 76859 sleeping for 5 seconds
1705515401.1482089: PID 76859 running execvpe(/usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x0,0x0 -H 192.168.253.129 -p 12865 -t TCP_STREAM -l 60 -F /dev/urandom -f m -- -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K cubic)

WARNING: Program exited non-zero.
Runner class: NetperfDemoRunner
Command: /usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x20,0x20 -H 192.168.253.129 -p 12865 -t TCP_MAERTS -l 60 -F /dev/urandom -f m   --    -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K reno
Return code: 255
Stdout: establish control: are you sure there is a netserver listening on 192.168.253.129 at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to 192.168.253.129 port 12865 address family AF_INET

Stderr: 1705515396.172329: PID 76866 sleeping for 5 seconds
1705515401.173337: PID 76866 running execvpe(/usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x20,0x20 -H 192.168.253.129 -p 12865 -t TCP_MAERTS -l 60 -F /dev/urandom -f m -- -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD -K reno)

WARNING: Program exited non-zero.
Runner class: NetperfDemoRunner
Command: /usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x0,0x0 -H 192.168.253.129 -p 12865 -t UDP_RR -l 70 -F /dev/urandom    -- -e 2   -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD
Return code: 255
Stdout: establish control: are you sure there is a netserver listening on 192.168.253.129 at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to 192.168.253.129 port 12865 address family AF_INET

Stderr: 1705515396.175402: PID 76867 sleeping for 0 seconds
1705515396.175904: PID 76867 running execvpe(/usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x0,0x0 -H 192.168.253.129 -p 12865 -t UDP_RR -l 70 -F /dev/urandom -- -e 2 -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD)

WARNING: Program exited non-zero.
Runner class: NetperfDemoRunner
Command: /usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0xc0,0xc0 -H 192.168.253.129 -p 12865 -t UDP_RR -l 70 -F /dev/urandom    -- -e 2   -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD
Return code: 255
Stdout: establish control: are you sure there is a netserver listening on 192.168.253.129 at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to 192.168.253.129 port 12865 address family AF_INET

Stderr: 1705515396.177443: PID 76869 sleeping for 0 seconds
1705515396.178078: PID 76869 running execvpe(/usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0xc0,0xc0 -H 192.168.253.129 -p 12865 -t UDP_RR -l 70 -F /dev/urandom -- -e 2 -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD)

WARNING: Program exited non-zero.
Runner class: NetperfDemoRunner
Command: /usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x20,0x20 -H 192.168.253.129 -p 12865 -t UDP_RR -l 70 -F /dev/urandom    -- -e 2   -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD
Return code: 255
Stdout: establish control: are you sure there is a netserver listening on 192.168.253.129 at port 12865?
establish_control could not establish the control connection from 0.0.0.0 port 0 address family AF_INET to 192.168.253.129 port 12865 address family AF_INET

Stderr: 1705515396.174199: PID 76868 sleeping for 0 seconds
1705515396.174826: PID 76868 running execvpe(/usr/local/bin/netperf -P 0 -v 0 -D -0.20 -4 -Y 0x20,0x20 -H 192.168.253.129 -p 12865 -t UDP_RR -l 70 -F /dev/urandom -- -e 2 -H 192.168.253.129 -k THROUGHPUT,LOCAL_CONG_CONTROL,REMOTE_CONG_CONTROL,TRANSPORT_MSS,LOCAL_TRANSPORT_RETRANS,REMOTE_TRANSPORT_RETRANS,LOCAL_SOCKET_TOS,REMOTE_SOCKET_TOS,DIRECTION,ELAPSED_TIME,PROTOCOL,LOCAL_SEND_SIZE,LOCAL_RECV_SIZE,REMOTE_SEND_SIZE,REMOTE_RECV_SIZE,LOCAL_BYTES_SENT,LOCAL_BYTES_RECVD,REMOTE_BYTES_SENT,REMOTE_BYTES_RECVD)

Traceback (most recent call last):
  File "/Users/richb/.pyenv/versions/3.7.4/lib/python3.7/site-packages/flent-2.1.1+git.1f6452a5-py3.7.egg/flent/gui.py", line 360, in read_log_queue
    msg = self.log_queue.get_nowait()
  File "/Users/richb/.pyenv/versions/3.7.4/lib/python3.7/multiprocessing/queues.py", line 126, in get_nowait
    return self.get(False)
  File "/Users/richb/.pyenv/versions/3.7.4/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/Users/richb/.pyenv/versions/3.7.4/lib/python3.7/site-packages/flent-2.1.1+git.1f6452a5-py3.7.egg/flent/runners.py", line 194, in __setstate__
    stdout_fd = state.pop("_stdout_fd")
KeyError: '_stdout_fd'
zsh: abort      /Users/richb/.pyenv/versions/3.7.4/bin/flent-gui
?134 flent %
```

**Comment by tohojo** [comment]
> Since we're talking about defaults, could the "Run new test" suggest RRUL by default? It's highly likely that this what newcomers want, and experienced users can choose their favorite. Thanks.

Sure, why not - added to the PR as well :)

**Comment by richb-hanover** [comment]
THANKS!
