### ISSUE TITLE
flent --list-tests fails if flent is installed by pip version 7.0.1

### ISSUE THREAD

**Issue by shakhat** [tohojo/flent#44]
The issue is reproducible on Ubuntu with the latest pip installed (7.0.1 as of now). The error is following:
$ flent --list-tests
Traceback (most recent call last):
  File "/usr/local/bin/flent", line 27, in <module>
    sys.exit(run_flent())
  File "/usr/local/lib/python2.7/dist-packages/flent/__init__.py", line 41, in run_flent
    settings = load(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/flent/settings.py", line 623, in load
    list_tests()
  File "/usr/local/lib/python2.7/dist-packages/flent/settings.py", line 656, in list_tests
    tests = sorted([os.path.splitext(i)[0] for i in os.listdir(TEST_PATH) if i.endswith('.conf')])
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tests'

The same works fine if flent is installed by pip 6.1 (or when it was installed by 6.1 and later pip upgraded)

The issue also reproducible in virtualenv created by version 13:
$ .venv/bin/flent --list-tests
Traceback (most recent call last):
  File ".venv/bin/flent", line 27, in <module>
    sys.exit(run_flent())
  File "/tmp/.venv/local/lib/python2.7/site-packages/flent/__init__.py", line 41, in run_flent
    settings = load(sys.argv[1:])
  File "/tmp/.venv/local/lib/python2.7/site-packages/flent/settings.py", line 623, in load
    list_tests()
  File "/tmp/.venv/local/lib/python2.7/site-packages/flent/settings.py", line 656, in list_tests
    tests = sorted([os.path.splitext(i)[0] for i in os.listdir(TEST_PATH) if i.endswith('.conf')])
OSError: [Errno 2] No such file or directory: '/tmp/.venv/local/lib/python2.7/site-packages/tests'
$ virtualenv --version
13.0.1

**Comment by tohojo** [comment]
Hmm, definitely need to figure out how to deal with setuptools et al.

In the meantime, if you pass `--no-binary=:all:` to pip when installing
things should work. Virtualenvs are probably still broken...

**Comment by tohojo** [comment]
Right, should hopefully be fixed in v0.11.1.

**Comment by shakhat** [comment]
Cool, it works! Thanks for quick response!

**Comment by tohojo** [comment]
No worries. Getting the packaging right has been a real PITA; glad it
works now. :)

Do you also get the man page installed correctly from pip?

**Comment by shakhat** [comment]
Yes, man page works fine too.

**Comment by tohojo** [comment]
Great!
