### ISSUE TITLE
latest git has broken rtt-fair test

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#56]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flent-0.12.4_git_4319244-py2.7.egg/flent/gui.py", line 530, in load_files
    widget.load_results(f)
  File "/usr/local/lib/python2.7/dist-packages/flent-0.12.4_git_4319244-py2.7.egg/flent/gui.py", line 1163, in load_results
    self.results = ResultSet.load_file(unicode(results))
  File "/usr/local/lib/python2.7/dist-packages/flent-0.12.4_git_4319244-py2.7.egg/flent/resultset.py", line 412, in load_file
    r = cls.load(fp, absolute)
  File "/usr/local/lib/python2.7/dist-packages/flent-0.12.4_git_4319244-py2.7.egg/flent/resultset.py", line 397, in load
    obj = cls.unserialise(json.load(fp), absolute, SUFFIX=ext)
  File "/usr/local/lib/python2.7/dist-packages/flent-0.12.4_git_4319244-py2.7.egg/flent/resultset.py", line 346, in unserialise
    metadata[t] = parse_date(metadata[t])
  File "/usr/local/lib/python2.7/dist-packages/flent-0.12.4_git_4319244-py2.7.egg/flent/util.py", line 71, in parse_date
    ts = time.mktime(dt.timetuple())
NameError: global name 'time' is not defined

**Comment by tohojo** [comment]
Dave Täht <notifications@github.com> writes:

> NameError: global name 'time' is not defined

Heh. Not specific to the RTT-fair test; should be fixed now.

-Toke
