### ISSUE TITLE
Error running flent on Windows

### ISSUE THREAD

**Issue by cklatsky** [tohojo/flent#58]
Hi,

I am trying to get flent & flent-gui to run on Windows.  I have installed Python, pip, setuptools, matplotlib, numpy, cycler, pytz, pyparsing, python-dateutil, and of course flent.  When I run I get the error shown below.  I am not even able to get the version output of flent.  The python version is shown below as well.  Any help is appreciated.

Thanks,
Carl

C:\Users\cklats000>python --version
Python 2.7.11rc1

C:\Users\cklats000>flent
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\flent.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\flent\__init__.py", line 39, in run_flent
    from flent import batch
  File "c:\python27\lib\site-packages\flent\batch.py", line 35, in <module>
    from flent import aggregators, formatters, resultset
  File "c:\python27\lib\site-packages\flent\aggregators.py", line 28, in <module>
    from . import runners, transformers
  File "c:\python27\lib\site-packages\flent\runners.py", line 143, in <module>
    class ProcessRunner(threading.Thread):
  File "c:\python27\lib\site-packages\flent\runners.py", line 238, in ProcessRunner
    def _handle_exitstatus(self, sts, _WIFSIGNALED=os.WIFSIGNALED,
AttributeError: 'module' object has no attribute 'WIFSIGNALED'

C:\Users\cklats000>
C:\Users\cklats000>flent --version
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\flent.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\flent\__init__.py", line 39, in run_flent
    from flent import batch
  File "c:\python27\lib\site-packages\flent\batch.py", line 35, in <module>
    from flent import aggregators, formatters, resultset
  File "c:\python27\lib\site-packages\flent\aggregators.py", line 28, in <module>
    from . import runners, transformers
  File "c:\python27\lib\site-packages\flent\runners.py", line 143, in <module>
    class ProcessRunner(threading.Thread):
  File "c:\python27\lib\site-packages\flent\runners.py", line 238, in ProcessRunner
    def _handle_exitstatus(self, sts, _WIFSIGNALED=os.WIFSIGNALED,
AttributeError: 'module' object has no attribute 'WIFSIGNALED'

**Comment by tohojo** [comment]
cklatsky <notifications@github.com> writes:

> I am trying to get flent & flent-gui to run on Windows. I have
> installed Python, pip, setuptools, matplotlib, numpy, cycler, pytz,
> pyparsing, python-dateutil, and of course flent. When I run I get the
> error shown below. I am not even able to get the version output of
> flent. The python version is shown below as well. Any help is
> appreciated.

Right, so this stems from the fact that Windows process handling is
completely different than on POSIX systems. Unfortunately, there doesn't
appear to be a quick fix; it seems I will have to rewrite the process
spawning code to work on Windows. Will try to find time for that.

I have added a workaround that will at least make flent runnable on
Windows (so you can plot etc). But running tests will not be possible
until I rework the process management code.

-Toke

**Comment by cklatsky** [comment]
If the workaround will allow me to run flent-gui, that would be ideal.  That is my main goal.  Thanks for the help on this issue.

**Comment by tohojo** [comment]
cklatsky <notifications@github.com> writes:

> If the workaround will allow me to run flent-gui, that would be ideal. That is
> my main goal. Thanks for the help on this issue.

Yes, that should be possible with the latest git head (barring any other
issues). Still untested, though, but do report any other bugs you may
encounter. And thanks for helping with debugging! :)

-Toke

**Comment by cklatsky** [comment]
Thanks.  Using the updated runners.py file, I was able to get output from flent for version without crashing.  But when I launch flent-gui, the command is accepted but no GUI appears on screen.

C:\Users\cklats000>flent --version
Flent v0.13.0.
Running on Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)].
Using matplotlib version 1.5.0 on numpy 1.10.1.
Using PyQt4 version 4.11.4

C:\Users\cklats000>flent-gui

C:\Users\cklats000>

**Comment by tohojo** [comment]
cklatsky <notifications@github.com> writes:

> Thanks. Using the updated runners.py file, I was able to get output from flent
> for version without crashing. But when I launch flent-gui, the command is
> accepted but no GUI appears on screen.

Hmm, I don't suppose it makes any difference to run `flent --gui`
instead of `flent-gui`?

-Toke

**Comment by tohojo** [comment]
Another thing to try is running `flent --gui --new-gui-instance` and see if that makes a difference.

**Comment by cklatsky** [comment]
Well, that did launch the GUI.  When I went to open a data file, I got several error popup windows.  The error output show below appeared in the DOS prompt window where I launched the GUI.

C:\exportaccounts>flent --gui --new-gui
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flent\gui.py", line 1127, in init_formatter
    self.formatter = PlotFormatter(self.settings)
  File "c:\python27\lib\site-packages\flent\formatters.py", line 242, in __init__
    settings.LOAD_MATPLOTLIBRC)
  File "c:\python27\lib\site-packages\flent\plotters.py", line 101, in init_matplotlib
    and not os.environ['HOME'] in matplotlib.matplotlib_fname() \
  File "c:\python27\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: u'HOME'
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flent\gui.py", line 544, in load_files
    widget.load_results(f)
  File "c:\python27\lib\site-packages\flent\gui.py", line 1181, in load_results
    self.init_formatter()
  File "c:\python27\lib\site-packages\flent\gui.py", line 1139, in init_formatter
    self.formatter = PlotFormatter(self.settings)
  File "c:\python27\lib\site-packages\flent\formatters.py", line 242, in __init__
    settings.LOAD_MATPLOTLIBRC)
  File "c:\python27\lib\site-packages\flent\plotters.py", line 101, in init_matplotlib
    and not os.environ['HOME'] in matplotlib.matplotlib_fname() \
  File "c:\python27\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: u'HOME'
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flent\gui.py", line 1343, in redraw
    self.formatter.init_plots()
AttributeError: 'NoneType' object has no attribute 'init_plots'

**Comment by tohojo** [comment]
Right, just pushed a couple of changes, one of which should fix the most recent error. Another might fix the "gui not launching without --new-gui" problem. Please test if you can launch the gui without that parameter now; otherwise I'll just disable that feature on Windows for now...

**Comment by cklatsky** [comment]
I upgraded to the new instance 'plotters.py' and that seemed to fix it.  I launch the gui using command line 'flent --gui --new-gui-instance'.  Running just 'flent --gui' gives an error and command 'flent-gui' never launches the GUI window.  But I am now able to launch the gui and load in a data file and see all the nice graphs and such.

Thanks for your help on this issue!

**Comment by tohojo** [comment]
Right, disabled that whole feature on Windows. You should be able to run without the --new-gui-instance parameter. 'flent-gui' might also work. Will try to find a windows box to test on and see if I can get the missing features restored.

And no problem; thanks for testing! :)

**Comment by cklatsky** [comment]
You're welcome and closing this issue item now.
