### ISSUE TITLE
tcp_4up blows up with the -f stats option

### ISSUE THREAD

**Issue by dtaht** [tohojo/flent#62]
$ flent -i tcp_4up-2016-03-11T171231.323289.*.flent.gz -f stats
Warning: Totals are computed as cumulative sum \* step size,
so spurious values wreck havoc with the results.
Results 
 Ping (ms) ICMP:
  Data points: 350
  Mean:        70.678097 ms
  Median:      73.189315 ms
  Min:         46.502090 ms
  Max:         89.323244 ms
  Std dev:     9.917411
  Variance:    98.355039
 TCP totals:
Traceback (most recent call last):
  File "/usr/local/bin/flent", line 9, in <module>
    load_entry_point('flent===0.14.0-git-5ebb2ae', 'console_scripts', 'flent')()
  File "/usr/local/lib/python2.7/dist-packages/flent-0.14.0_git_5ebb2ae-py2.7.egg/flent/**init**.py", line 50, in run_flent
    b.run()
  File "/usr/local/lib/python2.7/dist-packages/flent-0.14.0_git_5ebb2ae-py2.7.egg/flent/batch.py", line 497, in run
    return self.load_input(self.settings)
  File "/usr/local/lib/python2.7/dist-packages/flent-0.14.0_git_5ebb2ae-py2.7.egg/flent/batch.py", line 485, in load_input
    formatter.format(results)
  File "/usr/local/lib/python2.7/dist-packages/flent-0.14.0_git_5ebb2ae-py2.7.egg/flent/formatters.py", line 224, in format
    units = self.settings.DATA_SETS[s]['units']
KeyError: u'TCP totals'

**Comment by tohojo** [comment]
Can't reproduce this. Could you provide the data file that fails?

**Comment by tohojo** [comment]
Assuming this is fixed; please re-open if not.
