### ISSUE TITLE
rrul results graph render error

### ISSUE THREAD

**Issue by marlonjames** [tohojo/flent#81]
Ran the following command:
`$ flent rrul -p all_scaled -l 60 -H netperf.bufferbloat.net -t ntest1 -o ntest1.png`

Got this traceback:
> Traceback (most recent call last):
>   File "/usr/bin/flent", line 9, in <module>
>     load_entry_point('flent==0.15.0', 'console_scripts', 'run')()
>   File "/usr/share/flent/flent/__init__.py", line 50, in run_flent
>     b.run()
>   File "/usr/share/flent/flent/batch.py", line 545, in run
>     return self.run_test(self.settings, self.settings.DATA_DIR, True)
>   File "/usr/share/flent/flent/batch.py", line 471, in run_test
>     formatter.format([res])
>   File "/usr/share/flent/flent/formatters.py", line 283, in format
>     self.plotter.save(results)
>   File "/usr/share/flent/flent/plotters.py", line 427, in save
>     save_args = self.build_tight_layout(artists)
>   File "/usr/share/flent/flent/plotters.py", line 516, in build_tight_layout
>     self.figure.savefig(io.BytesIO())
>   File "/usr/lib/pymodules/python2.7/matplotlib/figure.py", line 1421, in savefig
>     self.canvas.print_figure(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 2220, in print_figure
>     **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line 505, in print_png
>     FigureCanvasAgg.draw(self)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line 451, in draw
>     self.figure.draw(self.renderer)
>   File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
>     draw(artist, renderer, *args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/figure.py", line 1034, in draw
>     func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
>     draw(artist, renderer, *args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2086, in draw
>     a.draw(renderer)
>   File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
>     draw(artist, renderer, *args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axis.py", line 1096, in draw
>     tick.draw(renderer)
>   File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
>     draw(artist, renderer, *args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axis.py", line 234, in draw
>     self.gridline.draw(renderer)
>   File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
>     draw(artist, renderer, *args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/lines.py", line 562, in draw
>     drawFunc(renderer, gc, tpath, affine.frozen())
>   File "/usr/lib/pymodules/python2.7/matplotlib/lines.py", line 938, in _draw_lines
>     self._lineFunc(renderer, gc, path, trans)
>   File "/usr/lib/pymodules/python2.7/matplotlib/lines.py", line 978, in _draw_solid
>     renderer.draw_path(gc, path, trans)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line 145, in draw_path
>     self._renderer.draw_path(gc, path, transform, rgbFace)
> TypeError: cannot return std::string from Unicode object

System info:
> 4.4.0-57-generic #78~14.04.1-Ubuntu SMP Sat Dec 10 00:14:47 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Installed flent using the tohojo/flent PPA:
> Package: flent
> Versions: 
> 0.15.0-1 (/var/lib/apt/lists/ppa.launchpad.net_tohojo_flent_ubuntu_dists_trusty_main_binary-amd64_Packages) (/var/lib/dpkg/status)
>  Description Language: 
>                  File: /var/lib/apt/lists/ppa.launchpad.net_tohojo_flent_ubuntu_dists_trusty_main_binary-amd64_Packages
>                   MD5: a196bdf560b42dbb863a32b2bd5d93f9
>  Description Language: en
>                  File: /var/lib/apt/lists/ppa.launchpad.net_tohojo_flent_ubuntu_dists_trusty_main_i18n_Translation-en
>                   MD5: a196bdf560b42dbb863a32b2bd5d93f9

 The .gz file was created for the test, but not the ntest1.png file. If I open the .gz file in flent-gui it fails to render and the same traceback is dumped to the console.

Matplotlib info:
> Package: python-matplotlib
> Versions: 
> 1.3.1-1ubuntu5 (/var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_trusty_universe_binary-amd64_Packages) (/var/lib/dpkg/status)
>  Description Language: 
>                  File: /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_trusty_universe_binary-amd64_Packages
>                   MD5: 2fece2cb7cd156344f82cc6d7070bac0
>  Description Language: en
>                  File: /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_trusty_universe_i18n_Translation-en
>                   MD5: 2fece2cb7cd156344f82cc6d7070bac0

**Comment by tohojo** [comment]
Hmm, I have a hunch why this happens; could you try building a plot with
all of `--no-legend` `--no-title` and `--no-annotation` please?

-Toke

**Comment by marlonjames** [comment]
Thanks for the response.

Ok, I tried running this:
>flent -i rrul-2016-12-31T113538.083154.ntest1.flent.gz -f plot rrul -p all --no-legend --no-title --no-annotation

And got a huge dump of errors:
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 276, in resize
>     self.show()
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 348, in draw
>     FigureCanvasAgg.draw(self)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line 451, in draw
>     self.figure.draw(self.renderer)
>   File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
>     draw(artist, renderer, *args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/figure.py", line 1034, in draw
>     func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
>     draw(artist, renderer, *args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2086, in draw
>     a.draw(renderer)
>   File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
>     draw(artist, renderer, *args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axis.py", line 1096, in draw
>     tick.draw(renderer)
>   File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
>     draw(artist, renderer, *args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axis.py", line 234, in draw
>     self.gridline.draw(renderer)
>   File "/usr/lib/pymodules/python2.7/matplotlib/artist.py", line 55, in draw_wrapper
>     draw(artist, renderer, *args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/lines.py", line 562, in draw
>     drawFunc(renderer, gc, tpath, affine.frozen())
>   File "/usr/lib/pymodules/python2.7/matplotlib/lines.py", line 938, in _draw_lines
>     self._lineFunc(renderer, gc, path, trans)
>   File "/usr/lib/pymodules/python2.7/matplotlib/lines.py", line 978, in _draw_solid
>     renderer.draw_path(gc, path, trans)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line 145, in draw_path
>     self._renderer.draw_path(gc, path, transform, rgbFace)
> TypeError: cannot return std::string from Unicode object
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError
> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1489, in __call__
>     return self.func(*args)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 380, in motion_notify_event
>     FigureCanvasBase.motion_notify_event(self, x, y, guiEvent=event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1834, in motion_notify_event
>     self.callbacks.process(s, event)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 527, in process
>     proxy(*args, **kwargs)
>   File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 405, in __call__
>     return mtd(*args, **kwargs)
>   File "/usr/share/flent/flent/plotters.py", line 1499, in on_move
>     s.on_move(event)
>   File "/usr/share/flent/flent/plotters.py", line 473, in on_move
>     self.update_axes(hovered)
>   File "/usr/share/flent/flent/plotters.py", line 491, in update_axes
>     a.axes.draw_artist(a)
>   File "/usr/lib/pymodules/python2.7/matplotlib/axes.py", line 2097, in draw_artist
>     assert self._cachedRenderer is not None
> AssertionError

Is that what you were looking for? I can try with a new test or a simpler plot type than "all".

Here's what the figure looked like when it popped up:
![figure1](https://cloud.githubusercontent.com/assets/14855711/21600031/eea8de50-d12a-11e6-8aed-3e9243214c35.png)

**Comment by tohojo** [comment]
Ah, seems I misread that backtrace. I added a workaround for what I
think is the issue here. Could you try out the git version, please?
(you can just clone the repo and use `python2 run-flent` in the base dir
in place of the installed Flent binary).

-Toke

**Comment by marlonjames** [comment]
Using current master as you suggested, the plot was created successfully with no errors.

![figure1_fix](https://cloud.githubusercontent.com/assets/14855711/21629041/5de6fce4-d1d9-11e6-8366-1a5d9d7af037.png)

Thanks for the quick response on this issue!
Is there a way to donate a few bucks towards the flent project? It's helped me kill my local bufferbloat problem.

**Comment by tohojo** [comment]
Awesome!

And you're welcome! I don't have a donation page, and your gratitude is plenty for me :). But thanks; if you want to help I'd appreciate it if you could test the upcoming release on your system to make sure the packaged version is also fixed - I'll try to get the release out in one of the coming days...
